dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - sourceline: 'ppa:keithw/glfw3'
    packages:
    - gcc-6
    - g++-6
    - cmake
    - libglfw3-dev
    - libglm-dev
    - libfftw3-dev
    - libpulse-dev
    - libconfig++-dev
    - libxdg-basedir-dev

script: mkdir -p build && cd build && cmake .. && make
