dist: trusty
sudo: false
language: cpp
compiler:
	- gcc
addons:
	apt:
		sources:
			- ubuntu-toolchain-r-test
			- george-edison55-cmake-3.x
		packages:
		- gcc-6
		- g++-6
		- cmake

script: mkdir -p build && cd build && cmake .. && make
