dist: trusty
sudo: false
language: cpp
compiler:
  - g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'
      - sourceline: 'ppa:keithw/glfw3'
      - sourceline: 'ppa:xorg-edgers/ppa'
      - sourceline: 'ppa:js-reynaud/libglm'
    packages:
    - gcc-6
    - g++-6
    - cmake
    - libglfw3-dev
    - mesa-common-dev
    - libglm-dev
    - libfftw3-dev
    - libpulse-dev
    - libconfig++-dev
    - libxdg-basedir-dev
script: cmake . && make
